name: Test

on:
  push:
    branches: [main, v*]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          command: uv sync && uv run scripts/ci.py --verbose --timeout 0
          pr_sha: ${{ github.sha }}
          merge: false
